default:
  ssh-path: internal

  local-editor:
    - neovide
    - --server
    - "{{SOCKET_PATH}}"

  server-env:
    - NVIM_APPNAME=nvchad-ide

servers:
  deku:
    nvim-cmd:
      - NVIM_APPNAME=nvchad-ide /usr/bin/env nvim
